---

- hosts: all
  become: true
  tasks:

  - name: create ansible user
    user:
      name: ansible
      groups: wheel


  - name: add ssh key for ansible user
    authorized_key:
      user: ansible
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCi3RFcTP/8zd9X14D2hyGDg9TdhT+KaYgO5ArEgg8lhLGnNbuMc1HnuWVE35FXxj6KWDpX66lBNZXJTr//SX/cBZcxrnapriW8jWaYJxzGHczbWxdcgoNRQi1n9CFzslMDHXbztEW8LxlIRPJmRVDj2Ja7W360629/sUcDdY0pO27IipclLaytppjshnbUC1y1g3zGEhe0qRAYZgfbGq5Ie/Nc3fZclw+OTl8k4U6H1Bbma9CIXlKde7/+m/LIQuJCPCCPGYAuFsUO1xc5OvfFK4OtZ+iFiJhszNXu6gubsDucFLPUBGmyOppdgajTxMaSS8QmV5SZVEfM6LYZ0C3T3A/gnEK71+DBg3kRDAKnfUYvud+gqPyJXDjlhi3FbGcDmRWrJJexkz+Rhm6k+ZFs0u/s0VsD3Mv0Qt9PLGTH2PsXAxphsKoGfBsbWFVeH3RwuEaHYqG/AuiM+9pMl6B6sluX1+8/NQNroTnfFliW2EVFMtkZNSNpb42tbo/AHSE= ansible-key"

  - name: add sudoers file for ansible
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440
