---

- hosts: all
  become: true
  tasks:
  - include_vars: users.yml

  - name: create users
    user: name="{{ item.username }}"
    with_items: "{{ users }}"


  - name: add ssh key for ansible user
    authorized_key: user="{{ item.username }}" key="{{ lookup('file', 'pub-keys/{{ item.username }}.pub') }}"
    with_items: "{{ users }}"
